#!/usr/bin/env python3
"""Combine and validate tree-sitter query files.

For each configured grammar, this script combines the grammar's query snippets
into a single ``queries/{language}.scm`` file and removes exact duplicate query
entries. It can then validate each combined query using ``tree-sitter query``
against ``/dev/null``.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
GRAMMAR_ROOT = REPO_ROOT / "data" / "tree-sitter" / "grammar"


@dataclass(frozen=True)
class LanguageConfig:
    directory: str
    output_name: str
    lang_name: str


LANGUAGES: tuple[LanguageConfig, ...] = (
    LanguageConfig("go", "go.scm", "go"),
    LanguageConfig("go.mod", "go.mod.scm", "gomod"),
    LanguageConfig("html", "html.scm", "html"),
    LanguageConfig("java", "java.scm", "java"),
    LanguageConfig("javascript", "javascript.scm", "javascript"),
    LanguageConfig("proto", "proto.scm", "proto"),
    LanguageConfig("python", "python.scm", "python"),
    LanguageConfig("sql", "sql.scm", "sql"),
    LanguageConfig("tsx", "tsx.scm", "tsx"),
    LanguageConfig("typescript", "typescript.scm", "typescript"),
)

ERROR_RE = re.compile(r"\b(error|warning)\b", re.IGNORECASE)


def _balance_delta(line: str) -> tuple[int, int]:
    paren = 0
    bracket = 0
    in_string = False
    escaped = False

    for char in line:
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue

        if char == ";":
            break
        if char == '"':
            in_string = True
        elif char == "(":
            paren += 1
        elif char == ")":
            paren -= 1
        elif char == "[":
            bracket += 1
        elif char == "]":
            bracket -= 1

    return paren, bracket


def _normalize_entry(entry: str) -> str:
    lines = []
    for line in entry.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(";"):
            continue
        lines.append(stripped)
    return "\n".join(lines)


def _query_entries(content: str) -> list[str]:
    entries: list[str] = []
    current: list[str] = []
    paren = 0
    bracket = 0

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(";"):
            continue

        current.append(line.rstrip())
        paren_delta, bracket_delta = _balance_delta(line)
        paren += paren_delta
        bracket += bracket_delta

        if current and paren == 0 and bracket == 0:
            entry = "\n".join(current).strip()
            if entry:
                entries.append(entry)
            current = []

    if current:
        entries.append("\n".join(current).strip())

    return entries


def _query_files(queries_dir: Path) -> list[Path]:
    return sorted(path for path in queries_dir.glob("*.scm") if path.is_file())


def combine_language(config: LanguageConfig) -> tuple[Path, int, int]:
    queries_dir = GRAMMAR_ROOT / config.directory / "queries"
    output_path = queries_dir / config.output_name
    seen: set[str] = set()
    entries: list[str] = []
    duplicate_count = 0

    for path in _query_files(queries_dir):
        for entry in _query_entries(path.read_text()):
            key = _normalize_entry(entry)
            if not key:
                continue
            if key in seen:
                duplicate_count += 1
                continue
            seen.add(key)
            entries.append(entry)

    body = "\n\n".join(entries).rstrip() + "\n"
    header = (
        f"; Combined tree-sitter query for {config.directory}.\n"
        "; Generated by scripts/combine_tree_sitter_queries.py.\n\n"
    )
    output_path.write_text(header + body)
    return output_path, len(entries), duplicate_count


def _find_library(config: LanguageConfig) -> Path | None:
    grammar_dir = GRAMMAR_ROOT / config.directory
    matches = sorted(grammar_dir.glob("*.so"))
    return matches[0] if matches else None


def validate_language(config: LanguageConfig) -> tuple[bool, str]:
    queries_dir = GRAMMAR_ROOT / config.directory / "queries"
    scm_path = queries_dir / config.output_name
    lib_path = _find_library(config)
    if lib_path is None:
        return False, f"{config.directory}: missing parser .so"
    if not scm_path.exists():
        return False, f"{config.directory}: missing {scm_path}"

    cmd = [
        "tree-sitter",
        "query",
        "--lib-path",
        str(lib_path),
        "--lang-name",
        config.lang_name,
        str(scm_path),
        "/dev/null",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    combined_output = "\n".join(part for part in (proc.stdout, proc.stderr) if part)
    diagnostics = [
        line.strip()
        for line in combined_output.splitlines()
        if ERROR_RE.search(line)
    ]
    if proc.returncode != 0 or diagnostics:
        detail = diagnostics[0] if diagnostics else f"tree-sitter exited {proc.returncode}"
        return False, f"{config.directory}: {detail}"
    return True, f"{config.directory}: valid"


def _selected_languages(names: list[str] | None) -> tuple[LanguageConfig, ...]:
    if not names:
        return LANGUAGES

    by_name = {config.directory: config for config in LANGUAGES}
    missing = sorted(set(names) - set(by_name))
    if missing:
        known = ", ".join(sorted(by_name))
        raise SystemExit(f"Unknown language(s): {', '.join(missing)}. Known: {known}")
    return tuple(by_name[name] for name in names)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Combine and validate tree-sitter query files."
    )
    parser.add_argument(
        "--lang",
        action="append",
        dest="languages",
        help="Language directory to process. May be passed more than once.",
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Validate existing combined files without regenerating them.",
    )
    parser.add_argument(
        "--no-validate",
        action="store_true",
        help="Only regenerate combined files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    configs = _selected_languages(args.languages)

    if not args.validate_only:
        for config in configs:
            output_path, entry_count, duplicate_count = combine_language(config)
            rel_path = output_path.relative_to(REPO_ROOT)
            print(
                f"{config.directory}: wrote {rel_path} "
                f"({entry_count} entries, {duplicate_count} duplicates removed)"
            )

    if args.no_validate:
        return 0

    failed = False
    for config in configs:
        ok, message = validate_language(config)
        print(("valid" if ok else "invalid") + f": {message}")
        failed = failed or not ok
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
